
  - name: disable module 
    ansible.builtin.command:  dnf module disable nginx -y 

  - name: enable module 
    ansible.builtin.command: dnf module enable nginx:1.24 -y 

  - name: install nginx 
    ansible.builtin.dnf:
      name: nginx
      state: installed 

  - name: remove html directory 
    ansible.builtin.file:
      path: /usr/share/nginx/html 
      state: absent
  
  - name: create html directory 
    ansible.builtin.file: 
      path: /usr/share/nginx/html 
      state: directory  

  - name: download the code 
    ansible.builtin.get_url: 
      url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip"
      dest: /tmp/"{{ component }}".zip 
  
  - name: unzipping the "{{ component }}" code
    ansible.builtin.unarchive:
      src: "/tmp/{{ component }}.zip"
      dest: /usr/share/nginx/html
      remote_src: yes 

  - name: remove default nginx 
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf 
      state: absent 

  - name: nginx config 
    ansible.builtin.template: 
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf 
  
  - name: start and enable service 
    ansible.builtin.service: 
      name: nginx 
      state: started 
      enabled: yes 
    notify:
     - Restart nginx

   
      


