- name: Stop the service 
  ansible.builtin.service:
    name: catalogue 
    state: absent 

- name: delete the app directory 
  ansible.builtin.file:
    path: /app
    state: absent 

- name: create the app directory 
  ansible.buitin.file: 
    path: /app 
    state: directory 

- name: download the code 
  ansible.builtin.get-url: 
    src:
    dest: 
    regex: true 

- name: downloading the dependencies 
  ansible.coumminty.general.npm:
    path: /app 

- name: start the service
  ansible.builtin.service: 
    name: catalogue 
    state: present      



